/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ConfidentialFlightBookingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addFlight"
      | "awardBonusPoints"
      | "bookFlight"
      | "bookings"
      | "cancelBooking"
      | "checkSeatAvailability"
      | "confirmBooking"
      | "flights"
      | "getBookingInfo"
      | "getContractBalance"
      | "getFlightInfo"
      | "getPassengerBookings"
      | "isAgeValid"
      | "isPaused"
      | "nextBookingId"
      | "nextFlightId"
      | "owner"
      | "passengerBookings"
      | "pause"
      | "paused"
      | "pauserSet"
      | "protocolId"
      | "unpause"
      | "updateFlightStatus"
      | "withdrawFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BookingCancelled"
      | "BookingConfirmed"
      | "BookingCreated"
      | "DecryptionRequested"
      | "FlightAdded"
      | "LoyaltyPointsAwarded"
      | "Paused"
      | "PaymentProcessed"
      | "RefundInitiated"
      | "RefundProcessed"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addFlight",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "awardBonusPoints",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bookFlight",
    values: [
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      boolean,
      BigNumberish,
      boolean,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "bookings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelBooking",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkSeatAvailability",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmBooking",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "flights",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBookingInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFlightInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPassengerBookings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAgeValid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "isPaused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nextBookingId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextFlightId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "passengerBookings",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "pauserSet", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateFlightStatus",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "addFlight", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "awardBonusPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bookFlight", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bookings", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelBooking",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkSeatAvailability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmBooking",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "flights", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBookingInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFlightInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPassengerBookings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAgeValid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextBookingId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextFlightId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "passengerBookings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pauserSet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateFlightStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
}

export namespace BookingCancelledEvent {
  export type InputTuple = [bookingId: BigNumberish];
  export type OutputTuple = [bookingId: bigint];
  export interface OutputObject {
    bookingId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BookingConfirmedEvent {
  export type InputTuple = [bookingId: BigNumberish];
  export type OutputTuple = [bookingId: bigint];
  export interface OutputObject {
    bookingId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BookingCreatedEvent {
  export type InputTuple = [
    bookingId: BigNumberish,
    flightId: BigNumberish,
    passenger: AddressLike
  ];
  export type OutputTuple = [
    bookingId: bigint,
    flightId: bigint,
    passenger: string
  ];
  export interface OutputObject {
    bookingId: bigint;
    flightId: bigint;
    passenger: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptionRequestedEvent {
  export type InputTuple = [requestId: BigNumberish, bookingId: BigNumberish];
  export type OutputTuple = [requestId: bigint, bookingId: bigint];
  export interface OutputObject {
    requestId: bigint;
    bookingId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FlightAddedEvent {
  export type InputTuple = [
    flightId: BigNumberish,
    origin: string,
    destination: string,
    airline: AddressLike
  ];
  export type OutputTuple = [
    flightId: bigint,
    origin: string,
    destination: string,
    airline: string
  ];
  export interface OutputObject {
    flightId: bigint;
    origin: string;
    destination: string;
    airline: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoyaltyPointsAwardedEvent {
  export type InputTuple = [bookingId: BigNumberish, passenger: AddressLike];
  export type OutputTuple = [bookingId: bigint, passenger: string];
  export interface OutputObject {
    bookingId: bigint;
    passenger: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [pauser: AddressLike];
  export type OutputTuple = [pauser: string];
  export interface OutputObject {
    pauser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentProcessedEvent {
  export type InputTuple = [bookingId: BigNumberish, passenger: AddressLike];
  export type OutputTuple = [bookingId: bigint, passenger: string];
  export interface OutputObject {
    bookingId: bigint;
    passenger: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundInitiatedEvent {
  export type InputTuple = [bookingId: BigNumberish, requestId: BigNumberish];
  export type OutputTuple = [bookingId: bigint, requestId: bigint];
  export interface OutputObject {
    bookingId: bigint;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundProcessedEvent {
  export type InputTuple = [
    bookingId: BigNumberish,
    seatNumber: BigNumberish,
    passenger: AddressLike
  ];
  export type OutputTuple = [
    bookingId: bigint,
    seatNumber: bigint,
    passenger: string
  ];
  export interface OutputObject {
    bookingId: bigint;
    seatNumber: bigint;
    passenger: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [pauser: AddressLike];
  export type OutputTuple = [pauser: string];
  export interface OutputObject {
    pauser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialFlightBooking extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialFlightBooking;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialFlightBookingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addFlight: TypedContractMethod<
    [
      _origin: string,
      _destination: string,
      _departureTime: BigNumberish,
      _arrivalTime: BigNumberish,
      _totalSeats: BigNumberish,
      _basePrice: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  awardBonusPoints: TypedContractMethod<
    [_bookingId: BigNumberish, _bonusPoints: BigNumberish],
    [void],
    "nonpayable"
  >;

  bookFlight: TypedContractMethod<
    [
      _flightId: BigNumberish,
      _passportNumber: BigNumberish,
      _encryptedName: string,
      _age: BigNumberish,
      _preferredSeat: BigNumberish,
      _hasSpecialNeeds: boolean,
      _frequentFlyerNumber: BigNumberish,
      _isVIP: boolean,
      _hasInsurance: boolean
    ],
    [void],
    "payable"
  >;

  bookings: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        string,
        string
      ] & {
        bookingId: bigint;
        flightId: bigint;
        passenger: string;
        paidAmount: string;
        seatNumber: string;
        bookingTime: bigint;
        isConfirmed: boolean;
        isCancelled: boolean;
        loyaltyPoints: string;
        hasInsurance: string;
      }
    ],
    "view"
  >;

  cancelBooking: TypedContractMethod<
    [_bookingId: BigNumberish],
    [void],
    "nonpayable"
  >;

  checkSeatAvailability: TypedContractMethod<
    [_flightId: BigNumberish, _seatNumber: BigNumberish],
    [boolean],
    "view"
  >;

  confirmBooking: TypedContractMethod<
    [_bookingId: BigNumberish],
    [void],
    "nonpayable"
  >;

  flights: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        string
      ] & {
        flightId: bigint;
        origin: string;
        destination: string;
        departureTime: bigint;
        arrivalTime: bigint;
        totalSeats: bigint;
        availableSeats: bigint;
        basePrice: string;
        isActive: boolean;
        airline: string;
      }
    ],
    "view"
  >;

  getBookingInfo: TypedContractMethod<
    [_bookingId: BigNumberish],
    [
      [bigint, string, bigint, boolean, boolean] & {
        flightId: bigint;
        passenger: string;
        bookingTime: bigint;
        isConfirmed: boolean;
        isCancelled: boolean;
      }
    ],
    "view"
  >;

  getContractBalance: TypedContractMethod<[], [bigint], "view">;

  getFlightInfo: TypedContractMethod<
    [_flightId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean, string] & {
        origin: string;
        destination: string;
        departureTime: bigint;
        arrivalTime: bigint;
        totalSeats: bigint;
        availableSeats: bigint;
        isActive: boolean;
        airline: string;
      }
    ],
    "view"
  >;

  getPassengerBookings: TypedContractMethod<
    [_passenger: AddressLike],
    [bigint[]],
    "view"
  >;

  isAgeValid: TypedContractMethod<[_age: BytesLike], [string], "nonpayable">;

  isPaused: TypedContractMethod<[], [boolean], "view">;

  nextBookingId: TypedContractMethod<[], [bigint], "view">;

  nextFlightId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  passengerBookings: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pauserSet: TypedContractMethod<[], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateFlightStatus: TypedContractMethod<
    [_flightId: BigNumberish, _isActive: boolean],
    [void],
    "nonpayable"
  >;

  withdrawFunds: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addFlight"
  ): TypedContractMethod<
    [
      _origin: string,
      _destination: string,
      _departureTime: BigNumberish,
      _arrivalTime: BigNumberish,
      _totalSeats: BigNumberish,
      _basePrice: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "awardBonusPoints"
  ): TypedContractMethod<
    [_bookingId: BigNumberish, _bonusPoints: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bookFlight"
  ): TypedContractMethod<
    [
      _flightId: BigNumberish,
      _passportNumber: BigNumberish,
      _encryptedName: string,
      _age: BigNumberish,
      _preferredSeat: BigNumberish,
      _hasSpecialNeeds: boolean,
      _frequentFlyerNumber: BigNumberish,
      _isVIP: boolean,
      _hasInsurance: boolean
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "bookings"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        boolean,
        boolean,
        string,
        string
      ] & {
        bookingId: bigint;
        flightId: bigint;
        passenger: string;
        paidAmount: string;
        seatNumber: string;
        bookingTime: bigint;
        isConfirmed: boolean;
        isCancelled: boolean;
        loyaltyPoints: string;
        hasInsurance: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelBooking"
  ): TypedContractMethod<[_bookingId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkSeatAvailability"
  ): TypedContractMethod<
    [_flightId: BigNumberish, _seatNumber: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "confirmBooking"
  ): TypedContractMethod<[_bookingId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "flights"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        boolean,
        string
      ] & {
        flightId: bigint;
        origin: string;
        destination: string;
        departureTime: bigint;
        arrivalTime: bigint;
        totalSeats: bigint;
        availableSeats: bigint;
        basePrice: string;
        isActive: boolean;
        airline: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBookingInfo"
  ): TypedContractMethod<
    [_bookingId: BigNumberish],
    [
      [bigint, string, bigint, boolean, boolean] & {
        flightId: bigint;
        passenger: string;
        bookingTime: bigint;
        isConfirmed: boolean;
        isCancelled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFlightInfo"
  ): TypedContractMethod<
    [_flightId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean, string] & {
        origin: string;
        destination: string;
        departureTime: bigint;
        arrivalTime: bigint;
        totalSeats: bigint;
        availableSeats: bigint;
        isActive: boolean;
        airline: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPassengerBookings"
  ): TypedContractMethod<[_passenger: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "isAgeValid"
  ): TypedContractMethod<[_age: BytesLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "isPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "nextBookingId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextFlightId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "passengerBookings"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pauserSet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateFlightStatus"
  ): TypedContractMethod<
    [_flightId: BigNumberish, _isActive: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "BookingCancelled"
  ): TypedContractEvent<
    BookingCancelledEvent.InputTuple,
    BookingCancelledEvent.OutputTuple,
    BookingCancelledEvent.OutputObject
  >;
  getEvent(
    key: "BookingConfirmed"
  ): TypedContractEvent<
    BookingConfirmedEvent.InputTuple,
    BookingConfirmedEvent.OutputTuple,
    BookingConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "BookingCreated"
  ): TypedContractEvent<
    BookingCreatedEvent.InputTuple,
    BookingCreatedEvent.OutputTuple,
    BookingCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DecryptionRequested"
  ): TypedContractEvent<
    DecryptionRequestedEvent.InputTuple,
    DecryptionRequestedEvent.OutputTuple,
    DecryptionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "FlightAdded"
  ): TypedContractEvent<
    FlightAddedEvent.InputTuple,
    FlightAddedEvent.OutputTuple,
    FlightAddedEvent.OutputObject
  >;
  getEvent(
    key: "LoyaltyPointsAwarded"
  ): TypedContractEvent<
    LoyaltyPointsAwardedEvent.InputTuple,
    LoyaltyPointsAwardedEvent.OutputTuple,
    LoyaltyPointsAwardedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentProcessed"
  ): TypedContractEvent<
    PaymentProcessedEvent.InputTuple,
    PaymentProcessedEvent.OutputTuple,
    PaymentProcessedEvent.OutputObject
  >;
  getEvent(
    key: "RefundInitiated"
  ): TypedContractEvent<
    RefundInitiatedEvent.InputTuple,
    RefundInitiatedEvent.OutputTuple,
    RefundInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "RefundProcessed"
  ): TypedContractEvent<
    RefundProcessedEvent.InputTuple,
    RefundProcessedEvent.OutputTuple,
    RefundProcessedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BookingCancelled(uint32)": TypedContractEvent<
      BookingCancelledEvent.InputTuple,
      BookingCancelledEvent.OutputTuple,
      BookingCancelledEvent.OutputObject
    >;
    BookingCancelled: TypedContractEvent<
      BookingCancelledEvent.InputTuple,
      BookingCancelledEvent.OutputTuple,
      BookingCancelledEvent.OutputObject
    >;

    "BookingConfirmed(uint32)": TypedContractEvent<
      BookingConfirmedEvent.InputTuple,
      BookingConfirmedEvent.OutputTuple,
      BookingConfirmedEvent.OutputObject
    >;
    BookingConfirmed: TypedContractEvent<
      BookingConfirmedEvent.InputTuple,
      BookingConfirmedEvent.OutputTuple,
      BookingConfirmedEvent.OutputObject
    >;

    "BookingCreated(uint32,uint32,address)": TypedContractEvent<
      BookingCreatedEvent.InputTuple,
      BookingCreatedEvent.OutputTuple,
      BookingCreatedEvent.OutputObject
    >;
    BookingCreated: TypedContractEvent<
      BookingCreatedEvent.InputTuple,
      BookingCreatedEvent.OutputTuple,
      BookingCreatedEvent.OutputObject
    >;

    "DecryptionRequested(uint256,uint32)": TypedContractEvent<
      DecryptionRequestedEvent.InputTuple,
      DecryptionRequestedEvent.OutputTuple,
      DecryptionRequestedEvent.OutputObject
    >;
    DecryptionRequested: TypedContractEvent<
      DecryptionRequestedEvent.InputTuple,
      DecryptionRequestedEvent.OutputTuple,
      DecryptionRequestedEvent.OutputObject
    >;

    "FlightAdded(uint32,string,string,address)": TypedContractEvent<
      FlightAddedEvent.InputTuple,
      FlightAddedEvent.OutputTuple,
      FlightAddedEvent.OutputObject
    >;
    FlightAdded: TypedContractEvent<
      FlightAddedEvent.InputTuple,
      FlightAddedEvent.OutputTuple,
      FlightAddedEvent.OutputObject
    >;

    "LoyaltyPointsAwarded(uint32,address)": TypedContractEvent<
      LoyaltyPointsAwardedEvent.InputTuple,
      LoyaltyPointsAwardedEvent.OutputTuple,
      LoyaltyPointsAwardedEvent.OutputObject
    >;
    LoyaltyPointsAwarded: TypedContractEvent<
      LoyaltyPointsAwardedEvent.InputTuple,
      LoyaltyPointsAwardedEvent.OutputTuple,
      LoyaltyPointsAwardedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PaymentProcessed(uint32,address)": TypedContractEvent<
      PaymentProcessedEvent.InputTuple,
      PaymentProcessedEvent.OutputTuple,
      PaymentProcessedEvent.OutputObject
    >;
    PaymentProcessed: TypedContractEvent<
      PaymentProcessedEvent.InputTuple,
      PaymentProcessedEvent.OutputTuple,
      PaymentProcessedEvent.OutputObject
    >;

    "RefundInitiated(uint32,uint256)": TypedContractEvent<
      RefundInitiatedEvent.InputTuple,
      RefundInitiatedEvent.OutputTuple,
      RefundInitiatedEvent.OutputObject
    >;
    RefundInitiated: TypedContractEvent<
      RefundInitiatedEvent.InputTuple,
      RefundInitiatedEvent.OutputTuple,
      RefundInitiatedEvent.OutputObject
    >;

    "RefundProcessed(uint32,uint32,address)": TypedContractEvent<
      RefundProcessedEvent.InputTuple,
      RefundProcessedEvent.OutputTuple,
      RefundProcessedEvent.OutputObject
    >;
    RefundProcessed: TypedContractEvent<
      RefundProcessedEvent.InputTuple,
      RefundProcessedEvent.OutputTuple,
      RefundProcessedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
