codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error

    patch:
      default:
        target: 80%
        threshold: 10%

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: no

flags:
  smart-contracts:
    paths:
      - contracts/
    carryforward: true

ignore:
  - "node_modules"
  - "test"
  - "scripts"
  - "deployments"
  - "frontend"
  - "*.config.js"
  - "*.config.ts"
  - "*.config.cts"
  - "hardhat.config.*.cts"
