/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PauserSetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAllPausers"
      | "getPauserAt"
      | "getPauserCount"
      | "isAuthorizedPauser"
      | "isPauser"
      | "pauserCount"
      | "pausers"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PauserSetInitialized"): EventFragment;

  encodeFunctionData(
    functionFragment: "getAllPausers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPauserAt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPauserCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedPauser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPauser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pauserCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pausers",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllPausers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPauserAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPauserCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedPauser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPauser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauserCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pausers", data: BytesLike): Result;
}

export namespace PauserSetInitializedEvent {
  export type InputTuple = [pausers: AddressLike[]];
  export type OutputTuple = [pausers: string[]];
  export interface OutputObject {
    pausers: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PauserSet extends BaseContract {
  connect(runner?: ContractRunner | null): PauserSet;
  waitForDeployment(): Promise<this>;

  interface: PauserSetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllPausers: TypedContractMethod<[], [string[]], "view">;

  getPauserAt: TypedContractMethod<[_index: BigNumberish], [string], "view">;

  getPauserCount: TypedContractMethod<[], [bigint], "view">;

  isAuthorizedPauser: TypedContractMethod<
    [_address: AddressLike],
    [boolean],
    "view"
  >;

  isPauser: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  pauserCount: TypedContractMethod<[], [bigint], "view">;

  pausers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllPausers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPauserAt"
  ): TypedContractMethod<[_index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getPauserCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isAuthorizedPauser"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPauser"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "pauserCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pausers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "PauserSetInitialized"
  ): TypedContractEvent<
    PauserSetInitializedEvent.InputTuple,
    PauserSetInitializedEvent.OutputTuple,
    PauserSetInitializedEvent.OutputObject
  >;

  filters: {
    "PauserSetInitialized(address[])": TypedContractEvent<
      PauserSetInitializedEvent.InputTuple,
      PauserSetInitializedEvent.OutputTuple,
      PauserSetInitializedEvent.OutputObject
    >;
    PauserSetInitialized: TypedContractEvent<
      PauserSetInitializedEvent.InputTuple,
      PauserSetInitializedEvent.OutputTuple,
      PauserSetInitializedEvent.OutputObject
    >;
  };
}
